---
- name: install acl package
  ansible.builtin.apt:
    name: acl
    state: present

- name: create promtail group
  ansible.builtin.group:
    name: promtail
    state: present

- name: create promtail user
  ansible.builtin.user:
    name: promtail
    groups:
      - promtail
      - systemd-journal
      - adm
    state: present
    system: true

- name: set facl to allow promtail user to read /var/log contents
  ansible.posix.acl:
    path: /var/log
    entity: promtail
    etype: user
    permissions: rX
    state: present

- name: make promtail user owner of /tmp/positions.yaml
  ansible.builtin.file:
    path: /tmp/positions.yaml
    owner: promtail
    group: promtail
    state: touch
    mode: 0750
  changed_when: false

- name: install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: check if binary exists
  ansible.builtin.stat:
    path: /usr/bin/promtail-linux-amd64
  register: binary

- name: check promtail version
  ansible.builtin.command: sudo promtail-linux-amd64 --version
  register: promtail_version_check
  when: binary.stat.exists
  changed_when: false

- name: install promtail if its not present
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v\
         {{  promtail_version  }}/promtail-linux-amd64.zip"
    dest: /usr/bin/
    remote_src: true
  tags:
    - loki
  when: (not binary.stat.exists)

- name: update promtail if different version is defined in variable
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v\
         {{  promtail_version  }}/promtail-linux-amd64.zip"
    dest: /usr/bin/
    remote_src: true
  tags:
    - loki
  when: (promtail_version_check | regex_search('\d.\d+.\d+') != promtail_version)
  notify: restart promtail

- name: template systemd unit file
  ansible.builtin.template:
    src: "{{ promtail_service_template }}"
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: 0755
  tags:
    - loki

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - loki

- name: make directory for promtail config
  ansible.builtin.file:
    path: /etc/promtail
    state: directory
    owner: root
    group: root
    mode: 0644

- name: template promtail config file
  ansible.builtin.template:
    src: "{{ promtail_config_template }}"
    dest: /usr/local/bin/config-promtail.yml
    owner: root
    group: root
    mode: 0644

- name: restart promtail
  become: true
  ansible.builtin.systemd:
    name: promtail
    enabled: true
    state: started
  changed_when: false
